{
 "title": "Nomad Cluster Metrics",
 "description": "Nomad built-in telemetry",
 "tags": [
  "nomad",
  "host",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Allocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", host=~\"$host\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\", host=~\"$host\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\", host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nomad_client_unallocated_memory{datacenter=~\"$datacenter\", host=~\"$host\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\", host=~\"$host\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\", host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nomad_client_unallocated_disk{datacenter=~\"$datacenter\", host=~\"$host\"}/(nomad_client_unallocated_disk{datacenter=~\"$datacenter\", host=~\"$host\"}+nomad_client_allocated_disk{datacenter=~\"$datacenter\", host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "$host Summary",
     "type": "natel-discrete-panel",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
     "repeat": "host",
     "targets": [
      {
       "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Migrating"
      },
      {
       "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Pending"
      },
      {
       "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Terminal"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime($host)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nomad_client_uptime{datacenter=~\"$datacenter\", host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "CPU Idle($host)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 2 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nomad_client_host_cpu_idle{datacenter=\"$datacenter\", host=\"$host\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Memory ($host)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 2 },
     "repeat": "host",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nomad_client_host_memory_total{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "nomad_client_host_memory_used{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "nomad_client_host_memory_available{datacenter=~\"$datacenter\", host=~\"$host\"}",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk Usage ($host)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 2 },
     "repeat": "host",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk)",
       "legendFormat": "Total - {{disk}}"
      },
      {
       "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk)",
       "legendFormat": "Available - {{disk}}"
      }
     ]
    },
    {
     "title": "Disk Inodes ($host)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 2 },
     "repeat": "host",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(nomad_client_host_disk_inodes_percent{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk)",
       "legendFormat": "{{disk}}"
      }
     ]
    }
   ]
  }
 ]
}