{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
    }
   },
   {
    "name": "ds_name",
    "label": "DS Name",
    "query": {
     "query": "label_values(vmware_datastore_freespace_size, ds_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host CPU usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "VM Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_mem_usage_average{host_name=~\"$esxhost\"}[5m]) / 4",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "Datastores Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{ds_name=~\"$ds_name\"}) - (vmware_datastore_freespace_size{ds_name=~\"$ds_name\"})) * 100 / (vmware_datastore_capacity_size{ds_name=~\"$ds_name\"})",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "Average VM CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{host_name=~\"$esxhost\"}",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "ESXi host uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"}",
     "legendFormat": "{{ host_name }}"
    }
   ]
  }
 ]
}